### ISSUE TITLE
Request: rouge version of doom-molokai heme 

### ISSUE THREAD

**Issue by Kwask94** [lepisma/rogue#3]
Hello,

I really loved your setup , it looks neat and amazing. 
to  the point the I spend two day trying to learn emacs <ex-vim user, trying to reporudce your results.. of cource I looked over and over into your dofiles as well as emacs layers but end up lost and faill trials.
but still trying.. tho 

I wonder if you be kind enough to tell me 
how to get from your dotfiles  just the two themes 
settings. make it as a theme and have spacemacs load it.

Hounstly it will mean a lot to me/ Thanks 

**Regards**

#### Why don't you just forke it, and build upon 
- I did, but it had few problems 
- the terminal version breaks 
- the switch of color takes longer
- swithing to light theme, the fonts and settings breaks. however the colors<Black> are okay.
- Plug and play for the community  can be an amazing thing.

**Comment by lepisma** [comment]
Hi, great to hear that you like the thing.

IIRC the only thing you need for that is in the [config.el](https://github.com/lepisma/rogue/blob/master/config.el) file. To make it a proper theme, I would have to change the _overrides_ and basically make a new theme. For now, I believe here are the steps:

1. Enable `theming` layer in spacemacs and install `doom-themes`
3. Load the code from config.el and then try switching (I guess you are already doing all these though)

I have been meaning to improve the theme setup but haven't got the time to do it. Other than the issues you mentioned (switching doesn't work smoothly, I haven't checked terminal thingy), there are a lot of other issues (for example 6 char hex colors don't work). I will keep on fixing these as I get time and let you know if any fixes affect the themes. Meanwhile, let me know if I can help in something else.

**Comment by Kwask94** [comment]
thank you, im currently working on iit, hopefull am about done
